"""03_group_creator_id

Revision ID: 6e52b96e29ae
Revises: d4db97a5952c
Create Date: 2026-08-26 18:43:45.531222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e52b96e29ae'
down_revision: Union[str, None] = 'd4db97a5952c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'creator',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('groups_creator_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['creator'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_creator_fkey'), 'groups', 'users', ['creator'], ['id'], ondelete='CASCADE')
    op.alter_column('groups', 'creator',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
