"""add operations and wallets models

Revision ID: 7b909f9a3286
Revises: 4e767668dbe0
Create Date: 2026-07-05 21:53:39.056544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b909f9a3286'
down_revision: Union[str, None] = '4e767668dbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('transaction_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_operation_transaction_id'), 'operation', ['transaction_id'], unique=True)
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_index(op.f('ix_operation_transaction_id'), table_name='operation')
    op.drop_column('operation', 'transaction_id')
    # ### end Alembic commands ###
