"""00_initial_migration

Revision ID: 87658c8418bb
Revises: 
Create Date: 2026-08-21 11:13:34.254375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87658c8418bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    currency_enum = postgresql.ENUM('rub', 'usd', 'eur', name='currencyenum')
    currency_enum.create(op.get_bind(), checkfirst=True)
    
    wallet_type_enum = postgresql.ENUM('debit', 'credit', name='wallettype')
    wallet_type_enum.create(op.get_bind(), checkfirst=True)
    
    operation_type_enum = postgresql.ENUM('expense', 'income', 'transfer', name='operationtype')
    operation_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('type', postgresql.ENUM('expense', 'income', 'transfer', name='operationtype'), nullable=False))
    op.add_column('operations', sa.Column('currency', postgresql.ENUM('rub', 'usd', 'eur', name='currencyenum'), nullable=False))
    op.add_column('wallets', sa.Column('currency', postgresql.ENUM('rub', 'usd', 'eur', name='currencyenum'), nullable=False))
    op.add_column('wallets', sa.Column('type', postgresql.ENUM('debit', 'credit', name='wallettype'), nullable=False))
    op.add_column('wallets', sa.Column('credit_limit', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'credit_limit')
    op.drop_column('wallets', 'type')
    op.drop_column('wallets', 'currency')
    op.drop_column('operations', 'currency')
    op.drop_column('operations', 'type')
    # ### end Alembic commands ###
