"""01_field_credit_limit-nullable=True

Revision ID: c91c710ac91d
Revises: 87658c8418bb
Create Date: 2026-08-21 12:01:28.480305

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c91c710ac91d"
down_revision: str | None = "87658c8418bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("wallets", "credit_limit", existing_type=sa.NUMERIC(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("wallets", "credit_limit", existing_type=sa.NUMERIC(), nullable=False)
    # ### end Alembic commands ###
