"""created_at=server_default

Revision ID: f834aeda7dbf
Revises: 7b909f9a3286
Create Date: 2026-07-08 23:43:26.090093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f834aeda7dbf'
down_revision: Union[str, None] = '7b909f9a3286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
